-- Add these to ox_inventory/data/items.lua, then restart ox_inventory.
-- Expanded fictional White Widow/Qbox roleplay item catalog. Keep names matching shared/config.lua.

['water'] = { label = 'Water', weight = 500, stack = true, close = true, client = { export = 'qbx_weedfactory.water' } },
['drinking_water'] = { label = 'Drinking Water', weight = 500, stack = true, close = true, client = { export = 'qbx_weedfactory.drinking_water' } },

['weed_soil'] = { label = 'Plant Soil', weight = 1000, stack = true, close = true },
['weed_water'] = { label = 'Plant Water', weight = 500, stack = true, close = true },
['empty_baggie'] = { label = 'Empty Baggie', weight = 5, stack = true, close = true },
['rolling_paper'] = { label = 'Rolling Paper', weight = 2, stack = true, close = true },
['king_rolling_paper'] = { label = 'King Size Rolling Paper', weight = 3, stack = true, close = true },
['infused_paper'] = { label = 'Infused Paper', weight = 4, stack = true, close = true },
['blunt_wrap'] = { label = 'Blunt Wrap', weight = 5, stack = true, close = true },
['honey_blunt_wrap'] = { label = 'Honey Blunt Wrap', weight = 5, stack = true, close = true },
['grape_blunt_wrap'] = { label = 'Grape Blunt Wrap', weight = 5, stack = true, close = true },
['premium_blunt_wrap'] = { label = 'Premium Blunt Wrap', weight = 6, stack = true, close = true },
['edible_base'] = { label = 'Edible Base', weight = 100, stack = true, close = true },
['brownie_mix'] = { label = 'Brownie Mix', weight = 120, stack = true, close = true },
['cookie_dough'] = { label = 'Cookie Dough', weight = 120, stack = true, close = true },
['gummy_base'] = { label = 'Gummy Base', weight = 100, stack = true, close = true },
['rice_treat_base'] = { label = 'Rice Treat Base', weight = 110, stack = true, close = true },
['cupcake_mix'] = { label = 'Cupcake Mix', weight = 120, stack = true, close = true },
['chocolate_bar_base'] = { label = 'Chocolate Bar Base', weight = 115, stack = true, close = true },
['cereal_bar_base'] = { label = 'Cereal Bar Base', weight = 110, stack = true, close = true },
['lollipop_base'] = { label = 'Lollipop Base', weight = 80, stack = true, close = true },
['glass_bong'] = { label = 'Glass Bong', weight = 850, stack = false, close = true },

-- Strains, flowers, rollables, edibles, and bags
['weed_seed_purple_punch'] = { label = 'Purple Punch Seed', weight = 1, stack = true, close = true },
['wet_weed_purple_punch'] = { label = 'Wet Purple Punch', weight = 25, stack = true, close = true },
['weed_purple_punch'] = { label = 'Purple Punch Flower', weight = 20, stack = true, close = true },
['joint_purple_punch'] = { label = 'Purple Punch Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_purple_punch' } },
['king_joint_purple_punch'] = { label = 'Purple Punch King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_purple_punch' } },
['infused_joint_purple_punch'] = { label = 'Purple Punch Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_purple_punch' } },
['blunt_purple_punch'] = { label = 'Purple Punch Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_purple_punch' } },
['honey_blunt_purple_punch'] = { label = 'Purple Punch Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_purple_punch' } },
['grape_blunt_purple_punch'] = { label = 'Purple Punch Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_purple_punch' } },
['ww_blunt_purple_punch'] = { label = 'Purple Punch White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_purple_punch' } },
['edible_brownie_purple_punch'] = { label = 'Purple Punch Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_purple_punch' } },
['edible_cookie_purple_punch'] = { label = 'Purple Punch Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_purple_punch' } },
['edible_gummies_purple_punch'] = { label = 'Purple Punch Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_purple_punch' } },
['edible_rice_treat_purple_punch'] = { label = 'Purple Punch Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_purple_punch' } },
['edible_cupcake_purple_punch'] = { label = 'Purple Punch Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_purple_punch' } },
['edible_chocolate_purple_punch'] = { label = 'Purple Punch Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_purple_punch' } },
['edible_cereal_bar_purple_punch'] = { label = 'Purple Punch Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_purple_punch' } },
['edible_lollipop_purple_punch'] = { label = 'Purple Punch Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_purple_punch' } },
['weed_bag_1g_purple_punch'] = { label = 'Purple Punch 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_purple_punch'] = { label = 'Purple Punch 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_purple_punch'] = { label = 'Purple Punch 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_purple_punch'] = { label = 'Purple Punch 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_cereal_milk'] = { label = 'Cereal Milk Seed', weight = 1, stack = true, close = true },
['wet_weed_cereal_milk'] = { label = 'Wet Cereal Milk', weight = 25, stack = true, close = true },
['weed_cereal_milk'] = { label = 'Cereal Milk Flower', weight = 20, stack = true, close = true },
['joint_cereal_milk'] = { label = 'Cereal Milk Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_cereal_milk' } },
['king_joint_cereal_milk'] = { label = 'Cereal Milk King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_cereal_milk' } },
['infused_joint_cereal_milk'] = { label = 'Cereal Milk Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_cereal_milk' } },
['blunt_cereal_milk'] = { label = 'Cereal Milk Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_cereal_milk' } },
['honey_blunt_cereal_milk'] = { label = 'Cereal Milk Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_cereal_milk' } },
['grape_blunt_cereal_milk'] = { label = 'Cereal Milk Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_cereal_milk' } },
['ww_blunt_cereal_milk'] = { label = 'Cereal Milk White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_cereal_milk' } },
['edible_brownie_cereal_milk'] = { label = 'Cereal Milk Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_cereal_milk' } },
['edible_cookie_cereal_milk'] = { label = 'Cereal Milk Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_cereal_milk' } },
['edible_gummies_cereal_milk'] = { label = 'Cereal Milk Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_cereal_milk' } },
['edible_rice_treat_cereal_milk'] = { label = 'Cereal Milk Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_cereal_milk' } },
['edible_cupcake_cereal_milk'] = { label = 'Cereal Milk Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_cereal_milk' } },
['edible_chocolate_cereal_milk'] = { label = 'Cereal Milk Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_cereal_milk' } },
['edible_cereal_bar_cereal_milk'] = { label = 'Cereal Milk Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_cereal_milk' } },
['edible_lollipop_cereal_milk'] = { label = 'Cereal Milk Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_cereal_milk' } },
['weed_bag_1g_cereal_milk'] = { label = 'Cereal Milk 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_cereal_milk'] = { label = 'Cereal Milk 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_cereal_milk'] = { label = 'Cereal Milk 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_cereal_milk'] = { label = 'Cereal Milk 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_lemon_tree'] = { label = 'Lemon Tree Seed', weight = 1, stack = true, close = true },
['wet_weed_lemon_tree'] = { label = 'Wet Lemon Tree', weight = 25, stack = true, close = true },
['weed_lemon_tree'] = { label = 'Lemon Tree Flower', weight = 20, stack = true, close = true },
['joint_lemon_tree'] = { label = 'Lemon Tree Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_lemon_tree' } },
['king_joint_lemon_tree'] = { label = 'Lemon Tree King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_lemon_tree' } },
['infused_joint_lemon_tree'] = { label = 'Lemon Tree Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_lemon_tree' } },
['blunt_lemon_tree'] = { label = 'Lemon Tree Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_lemon_tree' } },
['honey_blunt_lemon_tree'] = { label = 'Lemon Tree Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_lemon_tree' } },
['grape_blunt_lemon_tree'] = { label = 'Lemon Tree Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_lemon_tree' } },
['ww_blunt_lemon_tree'] = { label = 'Lemon Tree White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_lemon_tree' } },
['edible_brownie_lemon_tree'] = { label = 'Lemon Tree Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_lemon_tree' } },
['edible_cookie_lemon_tree'] = { label = 'Lemon Tree Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_lemon_tree' } },
['edible_gummies_lemon_tree'] = { label = 'Lemon Tree Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_lemon_tree' } },
['edible_rice_treat_lemon_tree'] = { label = 'Lemon Tree Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_lemon_tree' } },
['edible_cupcake_lemon_tree'] = { label = 'Lemon Tree Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_lemon_tree' } },
['edible_chocolate_lemon_tree'] = { label = 'Lemon Tree Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_lemon_tree' } },
['edible_cereal_bar_lemon_tree'] = { label = 'Lemon Tree Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_lemon_tree' } },
['edible_lollipop_lemon_tree'] = { label = 'Lemon Tree Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_lemon_tree' } },
['weed_bag_1g_lemon_tree'] = { label = 'Lemon Tree 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_lemon_tree'] = { label = 'Lemon Tree 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_lemon_tree'] = { label = 'Lemon Tree 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_lemon_tree'] = { label = 'Lemon Tree 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_kush_mintz'] = { label = 'Kush Mintz Seed', weight = 1, stack = true, close = true },
['wet_weed_kush_mintz'] = { label = 'Wet Kush Mintz', weight = 25, stack = true, close = true },
['weed_kush_mintz'] = { label = 'Kush Mintz Flower', weight = 20, stack = true, close = true },
['joint_kush_mintz'] = { label = 'Kush Mintz Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_kush_mintz' } },
['king_joint_kush_mintz'] = { label = 'Kush Mintz King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_kush_mintz' } },
['infused_joint_kush_mintz'] = { label = 'Kush Mintz Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_kush_mintz' } },
['blunt_kush_mintz'] = { label = 'Kush Mintz Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_kush_mintz' } },
['honey_blunt_kush_mintz'] = { label = 'Kush Mintz Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_kush_mintz' } },
['grape_blunt_kush_mintz'] = { label = 'Kush Mintz Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_kush_mintz' } },
['ww_blunt_kush_mintz'] = { label = 'Kush Mintz White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_kush_mintz' } },
['edible_brownie_kush_mintz'] = { label = 'Kush Mintz Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_kush_mintz' } },
['edible_cookie_kush_mintz'] = { label = 'Kush Mintz Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_kush_mintz' } },
['edible_gummies_kush_mintz'] = { label = 'Kush Mintz Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_kush_mintz' } },
['edible_rice_treat_kush_mintz'] = { label = 'Kush Mintz Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_kush_mintz' } },
['edible_cupcake_kush_mintz'] = { label = 'Kush Mintz Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_kush_mintz' } },
['edible_chocolate_kush_mintz'] = { label = 'Kush Mintz Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_kush_mintz' } },
['edible_cereal_bar_kush_mintz'] = { label = 'Kush Mintz Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_kush_mintz' } },
['edible_lollipop_kush_mintz'] = { label = 'Kush Mintz Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_kush_mintz' } },
['weed_bag_1g_kush_mintz'] = { label = 'Kush Mintz 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_kush_mintz'] = { label = 'Kush Mintz 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_kush_mintz'] = { label = 'Kush Mintz 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_kush_mintz'] = { label = 'Kush Mintz 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_apple_fritter'] = { label = 'Apple Fritter Seed', weight = 1, stack = true, close = true },
['wet_weed_apple_fritter'] = { label = 'Wet Apple Fritter', weight = 25, stack = true, close = true },
['weed_apple_fritter'] = { label = 'Apple Fritter Flower', weight = 20, stack = true, close = true },
['joint_apple_fritter'] = { label = 'Apple Fritter Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_apple_fritter' } },
['king_joint_apple_fritter'] = { label = 'Apple Fritter King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_apple_fritter' } },
['infused_joint_apple_fritter'] = { label = 'Apple Fritter Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_apple_fritter' } },
['blunt_apple_fritter'] = { label = 'Apple Fritter Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_apple_fritter' } },
['honey_blunt_apple_fritter'] = { label = 'Apple Fritter Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_apple_fritter' } },
['grape_blunt_apple_fritter'] = { label = 'Apple Fritter Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_apple_fritter' } },
['ww_blunt_apple_fritter'] = { label = 'Apple Fritter White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_apple_fritter' } },
['edible_brownie_apple_fritter'] = { label = 'Apple Fritter Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_apple_fritter' } },
['edible_cookie_apple_fritter'] = { label = 'Apple Fritter Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_apple_fritter' } },
['edible_gummies_apple_fritter'] = { label = 'Apple Fritter Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_apple_fritter' } },
['edible_rice_treat_apple_fritter'] = { label = 'Apple Fritter Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_apple_fritter' } },
['edible_cupcake_apple_fritter'] = { label = 'Apple Fritter Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_apple_fritter' } },
['edible_chocolate_apple_fritter'] = { label = 'Apple Fritter Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_apple_fritter' } },
['edible_cereal_bar_apple_fritter'] = { label = 'Apple Fritter Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_apple_fritter' } },
['edible_lollipop_apple_fritter'] = { label = 'Apple Fritter Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_apple_fritter' } },
['weed_bag_1g_apple_fritter'] = { label = 'Apple Fritter 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_apple_fritter'] = { label = 'Apple Fritter 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_apple_fritter'] = { label = 'Apple Fritter 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_apple_fritter'] = { label = 'Apple Fritter 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_sunset_sherbert'] = { label = 'Sunset Sherbert Seed', weight = 1, stack = true, close = true },
['wet_weed_sunset_sherbert'] = { label = 'Wet Sunset Sherbert', weight = 25, stack = true, close = true },
['weed_sunset_sherbert'] = { label = 'Sunset Sherbert Flower', weight = 20, stack = true, close = true },
['joint_sunset_sherbert'] = { label = 'Sunset Sherbert Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_sunset_sherbert' } },
['king_joint_sunset_sherbert'] = { label = 'Sunset Sherbert King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_sunset_sherbert' } },
['infused_joint_sunset_sherbert'] = { label = 'Sunset Sherbert Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_sunset_sherbert' } },
['blunt_sunset_sherbert'] = { label = 'Sunset Sherbert Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_sunset_sherbert' } },
['honey_blunt_sunset_sherbert'] = { label = 'Sunset Sherbert Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_sunset_sherbert' } },
['grape_blunt_sunset_sherbert'] = { label = 'Sunset Sherbert Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_sunset_sherbert' } },
['ww_blunt_sunset_sherbert'] = { label = 'Sunset Sherbert White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_sunset_sherbert' } },
['edible_brownie_sunset_sherbert'] = { label = 'Sunset Sherbert Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_sunset_sherbert' } },
['edible_cookie_sunset_sherbert'] = { label = 'Sunset Sherbert Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_sunset_sherbert' } },
['edible_gummies_sunset_sherbert'] = { label = 'Sunset Sherbert Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_sunset_sherbert' } },
['edible_rice_treat_sunset_sherbert'] = { label = 'Sunset Sherbert Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_sunset_sherbert' } },
['edible_cupcake_sunset_sherbert'] = { label = 'Sunset Sherbert Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_sunset_sherbert' } },
['edible_chocolate_sunset_sherbert'] = { label = 'Sunset Sherbert Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_sunset_sherbert' } },
['edible_cereal_bar_sunset_sherbert'] = { label = 'Sunset Sherbert Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_sunset_sherbert' } },
['edible_lollipop_sunset_sherbert'] = { label = 'Sunset Sherbert Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_sunset_sherbert' } },
['weed_bag_1g_sunset_sherbert'] = { label = 'Sunset Sherbert 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_sunset_sherbert'] = { label = 'Sunset Sherbert 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_sunset_sherbert'] = { label = 'Sunset Sherbert 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_sunset_sherbert'] = { label = 'Sunset Sherbert 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_tropical_punch'] = { label = 'Tropical Punch Seed', weight = 1, stack = true, close = true },
['wet_weed_tropical_punch'] = { label = 'Wet Tropical Punch', weight = 25, stack = true, close = true },
['weed_tropical_punch'] = { label = 'Tropical Punch Flower', weight = 20, stack = true, close = true },
['joint_tropical_punch'] = { label = 'Tropical Punch Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_tropical_punch' } },
['king_joint_tropical_punch'] = { label = 'Tropical Punch King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_tropical_punch' } },
['infused_joint_tropical_punch'] = { label = 'Tropical Punch Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_tropical_punch' } },
['blunt_tropical_punch'] = { label = 'Tropical Punch Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_tropical_punch' } },
['honey_blunt_tropical_punch'] = { label = 'Tropical Punch Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_tropical_punch' } },
['grape_blunt_tropical_punch'] = { label = 'Tropical Punch Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_tropical_punch' } },
['ww_blunt_tropical_punch'] = { label = 'Tropical Punch White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_tropical_punch' } },
['edible_brownie_tropical_punch'] = { label = 'Tropical Punch Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_tropical_punch' } },
['edible_cookie_tropical_punch'] = { label = 'Tropical Punch Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_tropical_punch' } },
['edible_gummies_tropical_punch'] = { label = 'Tropical Punch Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_tropical_punch' } },
['edible_rice_treat_tropical_punch'] = { label = 'Tropical Punch Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_tropical_punch' } },
['edible_cupcake_tropical_punch'] = { label = 'Tropical Punch Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_tropical_punch' } },
['edible_chocolate_tropical_punch'] = { label = 'Tropical Punch Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_tropical_punch' } },
['edible_cereal_bar_tropical_punch'] = { label = 'Tropical Punch Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_tropical_punch' } },
['edible_lollipop_tropical_punch'] = { label = 'Tropical Punch Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_tropical_punch' } },
['weed_bag_1g_tropical_punch'] = { label = 'Tropical Punch 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_tropical_punch'] = { label = 'Tropical Punch 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_tropical_punch'] = { label = 'Tropical Punch 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_tropical_punch'] = { label = 'Tropical Punch 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_mimosa'] = { label = 'Mimosa Seed', weight = 1, stack = true, close = true },
['wet_weed_mimosa'] = { label = 'Wet Mimosa', weight = 25, stack = true, close = true },
['weed_mimosa'] = { label = 'Mimosa Flower', weight = 20, stack = true, close = true },
['joint_mimosa'] = { label = 'Mimosa Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_mimosa' } },
['king_joint_mimosa'] = { label = 'Mimosa King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_mimosa' } },
['infused_joint_mimosa'] = { label = 'Mimosa Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_mimosa' } },
['blunt_mimosa'] = { label = 'Mimosa Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_mimosa' } },
['honey_blunt_mimosa'] = { label = 'Mimosa Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_mimosa' } },
['grape_blunt_mimosa'] = { label = 'Mimosa Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_mimosa' } },
['ww_blunt_mimosa'] = { label = 'Mimosa White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_mimosa' } },
['edible_brownie_mimosa'] = { label = 'Mimosa Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_mimosa' } },
['edible_cookie_mimosa'] = { label = 'Mimosa Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_mimosa' } },
['edible_gummies_mimosa'] = { label = 'Mimosa Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_mimosa' } },
['edible_rice_treat_mimosa'] = { label = 'Mimosa Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_mimosa' } },
['edible_cupcake_mimosa'] = { label = 'Mimosa Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_mimosa' } },
['edible_chocolate_mimosa'] = { label = 'Mimosa Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_mimosa' } },
['edible_cereal_bar_mimosa'] = { label = 'Mimosa Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_mimosa' } },
['edible_lollipop_mimosa'] = { label = 'Mimosa Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_mimosa' } },
['weed_bag_1g_mimosa'] = { label = 'Mimosa 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_mimosa'] = { label = 'Mimosa 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_mimosa'] = { label = 'Mimosa 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_mimosa'] = { label = 'Mimosa 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_devil_kiss'] = { label = 'Devil\'s Kiss Seed', weight = 1, stack = true, close = true },
['wet_weed_devil_kiss'] = { label = 'Wet Devil\'s Kiss', weight = 25, stack = true, close = true },
['weed_devil_kiss'] = { label = 'Devil\'s Kiss Flower', weight = 20, stack = true, close = true },
['joint_devil_kiss'] = { label = 'Devil\'s Kiss Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_devil_kiss' } },
['king_joint_devil_kiss'] = { label = 'Devil\'s Kiss King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_devil_kiss' } },
['infused_joint_devil_kiss'] = { label = 'Devil\'s Kiss Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_devil_kiss' } },
['blunt_devil_kiss'] = { label = 'Devil\'s Kiss Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_devil_kiss' } },
['honey_blunt_devil_kiss'] = { label = 'Devil\'s Kiss Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_devil_kiss' } },
['grape_blunt_devil_kiss'] = { label = 'Devil\'s Kiss Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_devil_kiss' } },
['ww_blunt_devil_kiss'] = { label = 'Devil\'s Kiss White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_devil_kiss' } },
['edible_brownie_devil_kiss'] = { label = 'Devil\'s Kiss Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_devil_kiss' } },
['edible_cookie_devil_kiss'] = { label = 'Devil\'s Kiss Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_devil_kiss' } },
['edible_gummies_devil_kiss'] = { label = 'Devil\'s Kiss Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_devil_kiss' } },
['edible_rice_treat_devil_kiss'] = { label = 'Devil\'s Kiss Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_devil_kiss' } },
['edible_cupcake_devil_kiss'] = { label = 'Devil\'s Kiss Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_devil_kiss' } },
['edible_chocolate_devil_kiss'] = { label = 'Devil\'s Kiss Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_devil_kiss' } },
['edible_cereal_bar_devil_kiss'] = { label = 'Devil\'s Kiss Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_devil_kiss' } },
['edible_lollipop_devil_kiss'] = { label = 'Devil\'s Kiss Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_devil_kiss' } },
['weed_bag_1g_devil_kiss'] = { label = 'Devil\'s Kiss 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_devil_kiss'] = { label = 'Devil\'s Kiss 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_devil_kiss'] = { label = 'Devil\'s Kiss 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_devil_kiss'] = { label = 'Devil\'s Kiss 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_white_widow'] = { label = 'White Widow Seed', weight = 1, stack = true, close = true },
['wet_weed_white_widow'] = { label = 'Wet White Widow', weight = 25, stack = true, close = true },
['weed_white_widow'] = { label = 'White Widow Flower', weight = 20, stack = true, close = true },
['joint_white_widow'] = { label = 'White Widow Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_white_widow' } },
['king_joint_white_widow'] = { label = 'White Widow King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_white_widow' } },
['infused_joint_white_widow'] = { label = 'White Widow Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_white_widow' } },
['blunt_white_widow'] = { label = 'White Widow Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_white_widow' } },
['honey_blunt_white_widow'] = { label = 'White Widow Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_white_widow' } },
['grape_blunt_white_widow'] = { label = 'White Widow Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_white_widow' } },
['ww_blunt_white_widow'] = { label = 'White Widow White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_white_widow' } },
['edible_brownie_white_widow'] = { label = 'White Widow Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_white_widow' } },
['edible_cookie_white_widow'] = { label = 'White Widow Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_white_widow' } },
['edible_gummies_white_widow'] = { label = 'White Widow Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_white_widow' } },
['edible_rice_treat_white_widow'] = { label = 'White Widow Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_white_widow' } },
['edible_cupcake_white_widow'] = { label = 'White Widow Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_white_widow' } },
['edible_chocolate_white_widow'] = { label = 'White Widow Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_white_widow' } },
['edible_cereal_bar_white_widow'] = { label = 'White Widow Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_white_widow' } },
['edible_lollipop_white_widow'] = { label = 'White Widow Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_white_widow' } },
['weed_bag_1g_white_widow'] = { label = 'White Widow 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_white_widow'] = { label = 'White Widow 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_white_widow'] = { label = 'White Widow 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_white_widow'] = { label = 'White Widow 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_blue_dream'] = { label = 'Blue Dream Seed', weight = 1, stack = true, close = true },
['wet_weed_blue_dream'] = { label = 'Wet Blue Dream', weight = 25, stack = true, close = true },
['weed_blue_dream'] = { label = 'Blue Dream Flower', weight = 20, stack = true, close = true },
['joint_blue_dream'] = { label = 'Blue Dream Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_blue_dream' } },
['king_joint_blue_dream'] = { label = 'Blue Dream King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_blue_dream' } },
['infused_joint_blue_dream'] = { label = 'Blue Dream Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_blue_dream' } },
['blunt_blue_dream'] = { label = 'Blue Dream Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_blue_dream' } },
['honey_blunt_blue_dream'] = { label = 'Blue Dream Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_blue_dream' } },
['grape_blunt_blue_dream'] = { label = 'Blue Dream Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_blue_dream' } },
['ww_blunt_blue_dream'] = { label = 'Blue Dream White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_blue_dream' } },
['edible_brownie_blue_dream'] = { label = 'Blue Dream Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_blue_dream' } },
['edible_cookie_blue_dream'] = { label = 'Blue Dream Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_blue_dream' } },
['edible_gummies_blue_dream'] = { label = 'Blue Dream Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_blue_dream' } },
['edible_rice_treat_blue_dream'] = { label = 'Blue Dream Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_blue_dream' } },
['edible_cupcake_blue_dream'] = { label = 'Blue Dream Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_blue_dream' } },
['edible_chocolate_blue_dream'] = { label = 'Blue Dream Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_blue_dream' } },
['edible_cereal_bar_blue_dream'] = { label = 'Blue Dream Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_blue_dream' } },
['edible_lollipop_blue_dream'] = { label = 'Blue Dream Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_blue_dream' } },
['weed_bag_1g_blue_dream'] = { label = 'Blue Dream 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_blue_dream'] = { label = 'Blue Dream 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_blue_dream'] = { label = 'Blue Dream 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_blue_dream'] = { label = 'Blue Dream 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_og_kush'] = { label = 'OG Kush Seed', weight = 1, stack = true, close = true },
['wet_weed_og_kush'] = { label = 'Wet OG Kush', weight = 25, stack = true, close = true },
['weed_og_kush'] = { label = 'OG Kush Flower', weight = 20, stack = true, close = true },
['joint_og_kush'] = { label = 'OG Kush Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_og_kush' } },
['king_joint_og_kush'] = { label = 'OG Kush King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_og_kush' } },
['infused_joint_og_kush'] = { label = 'OG Kush Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_og_kush' } },
['blunt_og_kush'] = { label = 'OG Kush Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_og_kush' } },
['honey_blunt_og_kush'] = { label = 'OG Kush Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_og_kush' } },
['grape_blunt_og_kush'] = { label = 'OG Kush Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_og_kush' } },
['ww_blunt_og_kush'] = { label = 'OG Kush White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_og_kush' } },
['edible_brownie_og_kush'] = { label = 'OG Kush Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_og_kush' } },
['edible_cookie_og_kush'] = { label = 'OG Kush Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_og_kush' } },
['edible_gummies_og_kush'] = { label = 'OG Kush Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_og_kush' } },
['edible_rice_treat_og_kush'] = { label = 'OG Kush Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_og_kush' } },
['edible_cupcake_og_kush'] = { label = 'OG Kush Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_og_kush' } },
['edible_chocolate_og_kush'] = { label = 'OG Kush Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_og_kush' } },
['edible_cereal_bar_og_kush'] = { label = 'OG Kush Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_og_kush' } },
['edible_lollipop_og_kush'] = { label = 'OG Kush Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_og_kush' } },
['weed_bag_1g_og_kush'] = { label = 'OG Kush 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_og_kush'] = { label = 'OG Kush 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_og_kush'] = { label = 'OG Kush 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_og_kush'] = { label = 'OG Kush 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_gelato'] = { label = 'Gelato Seed', weight = 1, stack = true, close = true },
['wet_weed_gelato'] = { label = 'Wet Gelato', weight = 25, stack = true, close = true },
['weed_gelato'] = { label = 'Gelato Flower', weight = 20, stack = true, close = true },
['joint_gelato'] = { label = 'Gelato Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_gelato' } },
['king_joint_gelato'] = { label = 'Gelato King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_gelato' } },
['infused_joint_gelato'] = { label = 'Gelato Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_gelato' } },
['blunt_gelato'] = { label = 'Gelato Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_gelato' } },
['honey_blunt_gelato'] = { label = 'Gelato Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_gelato' } },
['grape_blunt_gelato'] = { label = 'Gelato Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_gelato' } },
['ww_blunt_gelato'] = { label = 'Gelato White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_gelato' } },
['edible_brownie_gelato'] = { label = 'Gelato Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_gelato' } },
['edible_cookie_gelato'] = { label = 'Gelato Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_gelato' } },
['edible_gummies_gelato'] = { label = 'Gelato Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_gelato' } },
['edible_rice_treat_gelato'] = { label = 'Gelato Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_gelato' } },
['edible_cupcake_gelato'] = { label = 'Gelato Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_gelato' } },
['edible_chocolate_gelato'] = { label = 'Gelato Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_gelato' } },
['edible_cereal_bar_gelato'] = { label = 'Gelato Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_gelato' } },
['edible_lollipop_gelato'] = { label = 'Gelato Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_gelato' } },
['weed_bag_1g_gelato'] = { label = 'Gelato 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_gelato'] = { label = 'Gelato 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_gelato'] = { label = 'Gelato 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_gelato'] = { label = 'Gelato 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_runtz'] = { label = 'Runtz Seed', weight = 1, stack = true, close = true },
['wet_weed_runtz'] = { label = 'Wet Runtz', weight = 25, stack = true, close = true },
['weed_runtz'] = { label = 'Runtz Flower', weight = 20, stack = true, close = true },
['joint_runtz'] = { label = 'Runtz Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_runtz' } },
['king_joint_runtz'] = { label = 'Runtz King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_runtz' } },
['infused_joint_runtz'] = { label = 'Runtz Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_runtz' } },
['blunt_runtz'] = { label = 'Runtz Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_runtz' } },
['honey_blunt_runtz'] = { label = 'Runtz Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_runtz' } },
['grape_blunt_runtz'] = { label = 'Runtz Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_runtz' } },
['ww_blunt_runtz'] = { label = 'Runtz White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_runtz' } },
['edible_brownie_runtz'] = { label = 'Runtz Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_runtz' } },
['edible_cookie_runtz'] = { label = 'Runtz Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_runtz' } },
['edible_gummies_runtz'] = { label = 'Runtz Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_runtz' } },
['edible_rice_treat_runtz'] = { label = 'Runtz Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_runtz' } },
['edible_cupcake_runtz'] = { label = 'Runtz Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_runtz' } },
['edible_chocolate_runtz'] = { label = 'Runtz Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_runtz' } },
['edible_cereal_bar_runtz'] = { label = 'Runtz Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_runtz' } },
['edible_lollipop_runtz'] = { label = 'Runtz Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_runtz' } },
['weed_bag_1g_runtz'] = { label = 'Runtz 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_runtz'] = { label = 'Runtz 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_runtz'] = { label = 'Runtz 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_runtz'] = { label = 'Runtz 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_wedding_cake'] = { label = 'Wedding Cake Seed', weight = 1, stack = true, close = true },
['wet_weed_wedding_cake'] = { label = 'Wet Wedding Cake', weight = 25, stack = true, close = true },
['weed_wedding_cake'] = { label = 'Wedding Cake Flower', weight = 20, stack = true, close = true },
['joint_wedding_cake'] = { label = 'Wedding Cake Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_wedding_cake' } },
['king_joint_wedding_cake'] = { label = 'Wedding Cake King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_wedding_cake' } },
['infused_joint_wedding_cake'] = { label = 'Wedding Cake Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_wedding_cake' } },
['blunt_wedding_cake'] = { label = 'Wedding Cake Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_wedding_cake' } },
['honey_blunt_wedding_cake'] = { label = 'Wedding Cake Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_wedding_cake' } },
['grape_blunt_wedding_cake'] = { label = 'Wedding Cake Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_wedding_cake' } },
['ww_blunt_wedding_cake'] = { label = 'Wedding Cake White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_wedding_cake' } },
['edible_brownie_wedding_cake'] = { label = 'Wedding Cake Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_wedding_cake' } },
['edible_cookie_wedding_cake'] = { label = 'Wedding Cake Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_wedding_cake' } },
['edible_gummies_wedding_cake'] = { label = 'Wedding Cake Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_wedding_cake' } },
['edible_rice_treat_wedding_cake'] = { label = 'Wedding Cake Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_wedding_cake' } },
['edible_cupcake_wedding_cake'] = { label = 'Wedding Cake Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_wedding_cake' } },
['edible_chocolate_wedding_cake'] = { label = 'Wedding Cake Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_wedding_cake' } },
['edible_cereal_bar_wedding_cake'] = { label = 'Wedding Cake Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_wedding_cake' } },
['edible_lollipop_wedding_cake'] = { label = 'Wedding Cake Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_wedding_cake' } },
['weed_bag_1g_wedding_cake'] = { label = 'Wedding Cake 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_wedding_cake'] = { label = 'Wedding Cake 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_wedding_cake'] = { label = 'Wedding Cake 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_wedding_cake'] = { label = 'Wedding Cake 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_granddaddy_purple'] = { label = 'Granddaddy Purple Seed', weight = 1, stack = true, close = true },
['wet_weed_granddaddy_purple'] = { label = 'Wet Granddaddy Purple', weight = 25, stack = true, close = true },
['weed_granddaddy_purple'] = { label = 'Granddaddy Purple Flower', weight = 20, stack = true, close = true },
['joint_granddaddy_purple'] = { label = 'Granddaddy Purple Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_granddaddy_purple' } },
['king_joint_granddaddy_purple'] = { label = 'Granddaddy Purple King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_granddaddy_purple' } },
['infused_joint_granddaddy_purple'] = { label = 'Granddaddy Purple Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_granddaddy_purple' } },
['blunt_granddaddy_purple'] = { label = 'Granddaddy Purple Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_granddaddy_purple' } },
['honey_blunt_granddaddy_purple'] = { label = 'Granddaddy Purple Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_granddaddy_purple' } },
['grape_blunt_granddaddy_purple'] = { label = 'Granddaddy Purple Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_granddaddy_purple' } },
['ww_blunt_granddaddy_purple'] = { label = 'Granddaddy Purple White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_granddaddy_purple' } },
['edible_brownie_granddaddy_purple'] = { label = 'Granddaddy Purple Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_granddaddy_purple' } },
['edible_cookie_granddaddy_purple'] = { label = 'Granddaddy Purple Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_granddaddy_purple' } },
['edible_gummies_granddaddy_purple'] = { label = 'Granddaddy Purple Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_granddaddy_purple' } },
['edible_rice_treat_granddaddy_purple'] = { label = 'Granddaddy Purple Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_granddaddy_purple' } },
['edible_cupcake_granddaddy_purple'] = { label = 'Granddaddy Purple Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_granddaddy_purple' } },
['edible_chocolate_granddaddy_purple'] = { label = 'Granddaddy Purple Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_granddaddy_purple' } },
['edible_cereal_bar_granddaddy_purple'] = { label = 'Granddaddy Purple Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_granddaddy_purple' } },
['edible_lollipop_granddaddy_purple'] = { label = 'Granddaddy Purple Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_granddaddy_purple' } },
['weed_bag_1g_granddaddy_purple'] = { label = 'Granddaddy Purple 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_granddaddy_purple'] = { label = 'Granddaddy Purple 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_granddaddy_purple'] = { label = 'Granddaddy Purple 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_granddaddy_purple'] = { label = 'Granddaddy Purple 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_sour_diesel'] = { label = 'Sour Diesel Seed', weight = 1, stack = true, close = true },
['wet_weed_sour_diesel'] = { label = 'Wet Sour Diesel', weight = 25, stack = true, close = true },
['weed_sour_diesel'] = { label = 'Sour Diesel Flower', weight = 20, stack = true, close = true },
['joint_sour_diesel'] = { label = 'Sour Diesel Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_sour_diesel' } },
['king_joint_sour_diesel'] = { label = 'Sour Diesel King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_sour_diesel' } },
['infused_joint_sour_diesel'] = { label = 'Sour Diesel Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_sour_diesel' } },
['blunt_sour_diesel'] = { label = 'Sour Diesel Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_sour_diesel' } },
['honey_blunt_sour_diesel'] = { label = 'Sour Diesel Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_sour_diesel' } },
['grape_blunt_sour_diesel'] = { label = 'Sour Diesel Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_sour_diesel' } },
['ww_blunt_sour_diesel'] = { label = 'Sour Diesel White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_sour_diesel' } },
['edible_brownie_sour_diesel'] = { label = 'Sour Diesel Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_sour_diesel' } },
['edible_cookie_sour_diesel'] = { label = 'Sour Diesel Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_sour_diesel' } },
['edible_gummies_sour_diesel'] = { label = 'Sour Diesel Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_sour_diesel' } },
['edible_rice_treat_sour_diesel'] = { label = 'Sour Diesel Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_sour_diesel' } },
['edible_cupcake_sour_diesel'] = { label = 'Sour Diesel Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_sour_diesel' } },
['edible_chocolate_sour_diesel'] = { label = 'Sour Diesel Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_sour_diesel' } },
['edible_cereal_bar_sour_diesel'] = { label = 'Sour Diesel Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_sour_diesel' } },
['edible_lollipop_sour_diesel'] = { label = 'Sour Diesel Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_sour_diesel' } },
['weed_bag_1g_sour_diesel'] = { label = 'Sour Diesel 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_sour_diesel'] = { label = 'Sour Diesel 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_sour_diesel'] = { label = 'Sour Diesel 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_sour_diesel'] = { label = 'Sour Diesel 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_pineapple_express'] = { label = 'Pineapple Express Seed', weight = 1, stack = true, close = true },
['wet_weed_pineapple_express'] = { label = 'Wet Pineapple Express', weight = 25, stack = true, close = true },
['weed_pineapple_express'] = { label = 'Pineapple Express Flower', weight = 20, stack = true, close = true },
['joint_pineapple_express'] = { label = 'Pineapple Express Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_pineapple_express' } },
['king_joint_pineapple_express'] = { label = 'Pineapple Express King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_pineapple_express' } },
['infused_joint_pineapple_express'] = { label = 'Pineapple Express Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_pineapple_express' } },
['blunt_pineapple_express'] = { label = 'Pineapple Express Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_pineapple_express' } },
['honey_blunt_pineapple_express'] = { label = 'Pineapple Express Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_pineapple_express' } },
['grape_blunt_pineapple_express'] = { label = 'Pineapple Express Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_pineapple_express' } },
['ww_blunt_pineapple_express'] = { label = 'Pineapple Express White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_pineapple_express' } },
['edible_brownie_pineapple_express'] = { label = 'Pineapple Express Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_pineapple_express' } },
['edible_cookie_pineapple_express'] = { label = 'Pineapple Express Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_pineapple_express' } },
['edible_gummies_pineapple_express'] = { label = 'Pineapple Express Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_pineapple_express' } },
['edible_rice_treat_pineapple_express'] = { label = 'Pineapple Express Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_pineapple_express' } },
['edible_cupcake_pineapple_express'] = { label = 'Pineapple Express Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_pineapple_express' } },
['edible_chocolate_pineapple_express'] = { label = 'Pineapple Express Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_pineapple_express' } },
['edible_cereal_bar_pineapple_express'] = { label = 'Pineapple Express Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_pineapple_express' } },
['edible_lollipop_pineapple_express'] = { label = 'Pineapple Express Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_pineapple_express' } },
['weed_bag_1g_pineapple_express'] = { label = 'Pineapple Express 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_pineapple_express'] = { label = 'Pineapple Express 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_pineapple_express'] = { label = 'Pineapple Express 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_pineapple_express'] = { label = 'Pineapple Express 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_zkittlez'] = { label = 'Zkittlez Seed', weight = 1, stack = true, close = true },
['wet_weed_zkittlez'] = { label = 'Wet Zkittlez', weight = 25, stack = true, close = true },
['weed_zkittlez'] = { label = 'Zkittlez Flower', weight = 20, stack = true, close = true },
['joint_zkittlez'] = { label = 'Zkittlez Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_zkittlez' } },
['king_joint_zkittlez'] = { label = 'Zkittlez King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_zkittlez' } },
['infused_joint_zkittlez'] = { label = 'Zkittlez Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_zkittlez' } },
['blunt_zkittlez'] = { label = 'Zkittlez Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_zkittlez' } },
['honey_blunt_zkittlez'] = { label = 'Zkittlez Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_zkittlez' } },
['grape_blunt_zkittlez'] = { label = 'Zkittlez Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_zkittlez' } },
['ww_blunt_zkittlez'] = { label = 'Zkittlez White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_zkittlez' } },
['edible_brownie_zkittlez'] = { label = 'Zkittlez Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_zkittlez' } },
['edible_cookie_zkittlez'] = { label = 'Zkittlez Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_zkittlez' } },
['edible_gummies_zkittlez'] = { label = 'Zkittlez Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_zkittlez' } },
['edible_rice_treat_zkittlez'] = { label = 'Zkittlez Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_zkittlez' } },
['edible_cupcake_zkittlez'] = { label = 'Zkittlez Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_zkittlez' } },
['edible_chocolate_zkittlez'] = { label = 'Zkittlez Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_zkittlez' } },
['edible_cereal_bar_zkittlez'] = { label = 'Zkittlez Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_zkittlez' } },
['edible_lollipop_zkittlez'] = { label = 'Zkittlez Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_zkittlez' } },
['weed_bag_1g_zkittlez'] = { label = 'Zkittlez 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_zkittlez'] = { label = 'Zkittlez 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_zkittlez'] = { label = 'Zkittlez 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_zkittlez'] = { label = 'Zkittlez 28g Bag', weight = 350, stack = true, close = true },

['weed_seed_ice_cream_cake'] = { label = 'Ice Cream Cake Seed', weight = 1, stack = true, close = true },
['wet_weed_ice_cream_cake'] = { label = 'Wet Ice Cream Cake', weight = 25, stack = true, close = true },
['weed_ice_cream_cake'] = { label = 'Ice Cream Cake Flower', weight = 20, stack = true, close = true },
['joint_ice_cream_cake'] = { label = 'Ice Cream Cake Classic Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.joint_ice_cream_cake' } },
['king_joint_ice_cream_cake'] = { label = 'Ice Cream Cake King Size Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.king_joint_ice_cream_cake' } },
['infused_joint_ice_cream_cake'] = { label = 'Ice Cream Cake Infused Joint', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.infused_joint_ice_cream_cake' } },
['blunt_ice_cream_cake'] = { label = 'Ice Cream Cake Classic Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.blunt_ice_cream_cake' } },
['honey_blunt_ice_cream_cake'] = { label = 'Ice Cream Cake Honey Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.honey_blunt_ice_cream_cake' } },
['grape_blunt_ice_cream_cake'] = { label = 'Ice Cream Cake Grape Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.grape_blunt_ice_cream_cake' } },
['ww_blunt_ice_cream_cake'] = { label = 'Ice Cream Cake White Widow Signature Blunt', weight = 10, stack = true, close = true, client = { export = 'qbx_weedfactory.ww_blunt_ice_cream_cake' } },
['edible_brownie_ice_cream_cake'] = { label = 'Ice Cream Cake Brownie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_brownie_ice_cream_cake' } },
['edible_cookie_ice_cream_cake'] = { label = 'Ice Cream Cake Cookie', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cookie_ice_cream_cake' } },
['edible_gummies_ice_cream_cake'] = { label = 'Ice Cream Cake Gummy Bears', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_gummies_ice_cream_cake' } },
['edible_rice_treat_ice_cream_cake'] = { label = 'Ice Cream Cake Rice Treat', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_rice_treat_ice_cream_cake' } },
['edible_cupcake_ice_cream_cake'] = { label = 'Ice Cream Cake Cupcake', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cupcake_ice_cream_cake' } },
['edible_chocolate_ice_cream_cake'] = { label = 'Ice Cream Cake Chocolate Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_chocolate_ice_cream_cake' } },
['edible_cereal_bar_ice_cream_cake'] = { label = 'Ice Cream Cake Cereal Bar', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_cereal_bar_ice_cream_cake' } },
['edible_lollipop_ice_cream_cake'] = { label = 'Ice Cream Cake Lollipop', weight = 50, stack = true, close = true, client = { export = 'qbx_weedfactory.edible_lollipop_ice_cream_cake' } },
['weed_bag_1g_ice_cream_cake'] = { label = 'Ice Cream Cake 1g Bag', weight = 30, stack = true, close = true },
['weed_bag_35g_ice_cream_cake'] = { label = 'Ice Cream Cake 3.5g Bag', weight = 60, stack = true, close = true },
['weed_bag_7g_ice_cream_cake'] = { label = 'Ice Cream Cake 7g Bag', weight = 100, stack = true, close = true },
['weed_bag_28g_ice_cream_cake'] = { label = 'Ice Cream Cake 28g Bag', weight = 350, stack = true, close = true },

